site_name: MSL Equipment
site_description: Manage and interface with equipment in the laboratory
copyright: Copyright &copy; 2017 - 2025 Measurement Standards Laboratory of New Zealand
repo_url: https://github.com/MSLNZ/msl-equipment/
site_url: https://github.com/MSLNZ/msl-equipment/

theme:
  name: material
  language: en
  favicon: assets/images/favicon.ico
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    # Palette toggle for automatic mode
    - media: '(prefers-color-scheme)'
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to system preference

watch: [packages, src, CHANGELOG.md]

nav:
  - Overview:
    - index.md
    - release-notes.md
    - license.md
  - Getting Started:
    - getting-started/index.md
    - getting-started/equipment-registers.md
    - getting-started/connections.md
    - getting-started/configuration-files.md
  - Schema Classes:
    - schema/index.md
    - schema/acceptance_criteria.md
    - schema/accessories.md
    - schema/adjustment.md
    - schema/alteration.md
    - schema/any.md
    - schema/capital_expenditure.md
    - schema/competency.md
    - schema/completed_task.md
    - schema/component.md
    - schema/conditions.md
    - schema/cvd_equation.md
    - schema/deserialised.md
    - schema/digital_report.md
    - schema/equation.md
    - schema/equipment.md
    - schema/file.md
    - schema/financial.md
    - schema/firmware.md
    - schema/maintenance.md
    - schema/measurand.md
    - schema/performance_check.md
    - schema/planned_task.md
    - schema/quality_manual.md
    - schema/reference_materials.md
    - schema/register.md
    - schema/report.md
    - schema/specifications.md
    - schema/specified_requirements.md
    - schema/status.md
    - schema/table.md
  - API:
    - api/index.md
    - api/config.md
    - api/connection.md
    - api/readings.md
    - api/enumerations.md
    - api/exceptions.md
    - api/types.md
    - Interfaces:
      - api/interfaces/index.md
      - api/interfaces/gpib.md
      - api/interfaces/hislip.md
      - api/interfaces/prologix.md
      - api/interfaces/sdk.md
      - api/interfaces/serial.md
      - api/interfaces/socket.md
      - api/interfaces/usb.md
      - api/interfaces/vxi11.md
      - api/interfaces/zeromq.md
    - Backends:
      - api/backends/index.md
      - api/backends/nidaq.md
      - api/backends/pyvisa.md
  - Resources:
    - resources/index.md
    - Aim-TTi:
      - resources/aim-tti/mx_series.md
    - Avantes:
      - resources/avantes/avaspec.md
    - CMI:
      - resources/cmi/sia3.md
    - DataRay:
      - resources/dataray/wincamd.md
    - Electron Dynamics:
      - resources/electron_dynamics/tc_series.md
    - Energetiq:
      - resources/energetiq/eq99.md
    - Greisinger:
      - resources/greisinger/gmh3000.md
    - Isotech:
      - resources/isotech/millik.md
    - MKS Instruments:
      - resources/mks/pr4000b.md
    - NKT Photonics:
      - resources/nkt/nktpdll.md
    - OMEGA:
      - resources/omega/ithx.md
    - OptoSigma:
      - resources/optosigma/shot702.md
    - Optronic Laboratories:
      - resources/optronic_labs/ol756.md
      - resources/optronic_labs/olxxa.md
    - Pico Technology:
      - resources/picotech/picoscope.md
      - resources/picotech/pt104.md
      - resources/picotech/types.md
    - Princeton Instruments:
      - resources/princeton_instruments/arc_instrument.md
    - Raicol Crystals:
      - resources/raicol/tec.md
    - Thorlabs:
      - resources/thorlabs/fwxx2c.md
    - Vaisala:
      - resources/vaisala/ptb330.md
      - resources/vaisala/ptu300.md
    - resources/multi_message_based.md
    - resources/types.md
  - Validate: validate.md
  - WebApp: webapp.md

markdown_extensions:
  - admonition  # enables: !!! tip
  - attr_list  # enables: [link](url){:target="_blank"} and {: #rename-permalink }
  - pymdownx.arithmatex:  # enables MathJax, requires docs/javascripts/arithmatex.js and extra_javascript below
      generic: true
  - pymdownx.details  # enables collapsable admonition
  - pymdownx.snippets  # enables: --8<--
  - pymdownx.superfences  # enables tabs in admonition
  - pymdownx.tabbed:
      alternate_style: true  # tabs look better on narrower screen sizes (like mobile)
  - toc:
      permalink: "Â¤"

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          inventories:
            - url: https://docs.python.org/3/objects.inv
              domains: [std, py]
            - url: https://numpy.org/doc/stable/objects.inv
              domains: [std, py]
            - url: https://mslnz.github.io/equipment-register-schema/latest/objects.inv
              domains: [xsd]
            - url: https://gtc.readthedocs.io/en/stable/objects.inv
            - url: https://mslnz.github.io/msl-io/latest/objects.inv
            - url: https://mslnz.github.io/msl-loadlib/latest/objects.inv
            - url: https://pyvisa.readthedocs.io/en/stable/objects.inv
            - url: https://nidaqmx-python.readthedocs.io/en/stable/objects.inv
            - url: https://pyzmq.readthedocs.io/en/stable/objects.inv
            - url: https://pyserial.readthedocs.io/en/stable/objects.inv
          options:
            # General
            show_source: true

            # Headings
            show_root_toc_entry: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true

            # Members
            filters: ["!^_"]
            inherited_members: true

            # Docstrings
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true

            # Signatures
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true

extra:
  version:
    provider: mike
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/MSLNZ/msl-equipment
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/msl-equipment/

extra_javascript:
  - javascripts/arithmatex.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@4.0.0/tex-mml-chtml.js
