name: CI

on: [push, pull_request]

env:
  PY_COLORS: 1
  COLUMNS: 110

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install locales (Ubuntu)
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y language-pack-en language-pack-de
      - name: Install libusb-1.0 (Windows)
        if: ${{ matrix.os == 'windows' }}
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://github.com/libusb/libusb/releases/download/v1.0.29/libusb-1.0.29.7z -OutFile libusb.7z
          7z e libusb.7z -oC:\Windows\System32 VS2022\MS64\dll\libusb-1.0.dll
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: false
      - name: Run tests
        run: uv run --all-packages --python ${{ matrix.python-version }} --no-dev --group test -- pytest
